# Generated by Django 2.2.16 on 2022-04-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220417_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
